spring:
  profiles:
    active: local

  port: 8080

springdoc:
  packages-to-scan: com.groomiz.billage
  default-consumes-media-type: application/json;charset=UTF-8
  default-produces-media-type: application/json;charset=UTF-8
  swagger-ui:
    path: /
    disable-swagger-default-url: true
    display-request-duration: true
    operations-sorter: alpha

